on:
  workflow_dispatch:
    inputs:
      keycloak_version:
        description: Keycloak version
        required: true
      keycloak_hmac_sha_version:
        description: Keycloak HMAC SHA version
        required: true
        default: 1.0.0

name: Docker

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew jar -Pdependency.keycloak.version=${{ github.event.inputs.keycloak_version }}
      - run: cp build/libs/keycloak-hmac-sha-${{ github.event.inputs.keycloak_hmac_sha_version }}.jar docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: docker
          build-args: |
            keycloak_version=${{ github.event.inputs.keycloak_version }}
            keycloak_hmac_sha_version=${{ github.event.inputs.keycloak_hmac_sha_version }}
          push: true
          tags: lanmark/keycloak-hmac-sha:${{ github.event.inputs.keycloak_version }}_${{ github.event.inputs.keycloak_hmac_sha_version }},lanmark/keycloak-hmac-sha:latest
